version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Assuming package.json is in the root
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
